// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC42UeGzfiCmL7xm3_TnumW9FbGbZKhFJ4',
    appId: '1:978485068745:web:94e986c50b16a5f5f99e18',
    messagingSenderId: '978485068745',
    projectId: 'mynotes-flutter-project-0103',
    authDomain: 'mynotes-flutter-project-0103.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-0103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW63x9R8cm9fN8hrHPUIlS1A20QKeMWBw',
    appId: '1:978485068745:android:d858360f59b11c93f99e18',
    messagingSenderId: '978485068745',
    projectId: 'mynotes-flutter-project-0103',
    storageBucket: 'mynotes-flutter-project-0103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqUYvTLKfRunJ0BFKPWNCEC4xyaI2X7Y',
    appId: '1:978485068745:ios:d7820eb971daa572f99e18',
    messagingSenderId: '978485068745',
    projectId: 'mynotes-flutter-project-0103',
    storageBucket: 'mynotes-flutter-project-0103.appspot.com',
    iosClientId:
        '978485068745-5m4tppiu02fgr3n5107evtn1tiaaiqa4.apps.googleusercontent.com',
    iosBundleId: 'com.rin.mynotes',
  );
}
